"use client";

import { useState } from "react";
import { Activity, AlertTriangle, CheckCheck, Clock3, Search } from "lucide-react";
import { AdminPanel, AGENT_LABELS, TASK_LABELS, TaskStatus, adminTime, taskDuration } from "./admin-panel";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import type { PlatformSnapshot } from "@/types/admin";

export function TaskMonitor({ snapshot, dataSource }: { snapshot: PlatformSnapshot; dataSource: string }) {
  const [search, setSearch] = useState(""), [status, setStatus] = useState("all"), [agent, setAgent] = useState("all"), [page, setPage] = useState(0), [expanded, setExpanded] = useState<string | null>(null);
  const filtered = snapshot.recentTasks.filter(row => (status === "all" || row.status === status) && (agent === "all" || row.agentType === agent) && `${row.title} ${row.businessName} ${AGENT_LABELS[row.agentType] ?? row.agentType}`.toLowerCase().includes(search.toLowerCase()));
  const lastPage = Math.max(0, Math.ceil(filtered.length / 15) - 1), currentPage = Math.min(page, lastPage);
  const rows = filtered.slice(currentPage * 15, (currentPage + 1) * 15), ended = snapshot.completed + snapshot.failed;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] tracking-[0.2em] text-cyan-400/70">AI OPERATIONS</p><h2 className="mt-1 text-2xl font-bold">AI 运行监控</h2><p className="mt-2 text-xs text-slate-400">查看执行结果、耗时与错误摘要，发现需要处理的任务。</p></div><span className="rounded-full border border-cyan-400/15 bg-cyan-400/10 px-3 py-1.5 text-[11px] text-cyan-200">{dataSource === "mock" ? "内存演示环境" : "平台实际任务记录"} · {adminTime(snapshot.updatedAt)}</span></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ title: "执行成功", value: snapshot.completed, desc: `${ended ? (snapshot.completed / ended * 100).toFixed(1) : "—"}% 成功率`, icon: CheckCheck }, { title: "执行失败", value: snapshot.failed, desc: "点击下方任务查看错误摘要", icon: AlertTriangle }, { title: "当前执行 / 等待", value: `${snapshot.running} / ${snapshot.queued}`, desc: `${snapshot.skipped} 个跳过任务单独记录`, icon: Activity }, { title: "平均任务耗时", value: taskDuration(snapshot.averageDurationMs), desc: "只统计成功或失败且有耗时的任务", icon: Clock3 }].map(({ title, value, desc, icon: Icon }) => <div key={title} className="rounded-2xl border border-cyan-400/15 bg-[#102b44] p-5"><p className="flex items-center justify-between text-xs text-slate-400">{title}<Icon className="size-5 text-cyan-300" /></p><p className="mt-4 font-mono text-3xl text-white">{value}</p><p className="mt-3 text-[10px] text-slate-500">{desc}</p></div>)}</div>
    <AdminPanel title="任务执行记录" eyebrow="TASK HISTORY" action={<span className="text-[11px] text-slate-400">最近 {snapshot.recentTasks.length} 条</span>}>
      <div className="mb-5 grid gap-3 md:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute top-3 left-3 size-4 text-slate-500" /><Input aria-label="搜索任务或商户" placeholder="搜索任务名称、商户或 AI 岗位" value={search} onChange={e => { setSearch(e.target.value); setPage(0); }} className="pl-9" /></div><Select aria-label="筛选任务状态" value={status} onChange={e => { setStatus(e.target.value); setPage(0); }}><option value="all">全部状态</option>{Object.entries(TASK_LABELS).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</Select><Select aria-label="筛选 AI 岗位" value={agent} onChange={e => { setAgent(e.target.value); setPage(0); }}><option value="all">全部 AI 岗位</option>{[...new Set(snapshot.recentTasks.map(row => row.agentType))].map(value => <option key={value} value={value}>{AGENT_LABELS[value] ?? value}</option>)}</Select></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b border-white/10 bg-white/3 text-slate-400">{["任务", "商户", "AI 岗位", "状态", "耗时", "开始时间", "详情"].map(label => <th key={label} className="px-3 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{rows.map(row => <TaskRow key={row.id} row={row} expanded={expanded === row.id} toggle={() => setExpanded(expanded === row.id ? null : row.id)} />)}</tbody></table>{!rows.length && <p className="py-12 text-center text-sm text-slate-500">{search || status !== "all" || agent !== "all" ? "没有符合筛选条件的任务" : "暂无任务执行记录"}</p>}</div>
      <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs text-slate-400"><span>{filtered.length} 条匹配记录 · 每页 15 条</span><div className="flex items-center gap-3"><Button size="sm" variant="outline" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>上一页</Button><span>{currentPage + 1} / {lastPage + 1}</span><Button size="sm" variant="outline" disabled={currentPage === lastPage} onClick={() => setPage(currentPage + 1)}>下一页</Button></div></div>
    </AdminPanel>
  </div>;
}

function TaskRow({ row, expanded, toggle }: { row: PlatformSnapshot["recentTasks"][number]; expanded: boolean; toggle: () => void }) {
  return <><tr className="border-b border-white/5 hover:bg-white/3"><td className="max-w-[280px] truncate px-3 py-4" title={row.title}>{row.title}</td><td className="max-w-[160px] truncate px-3 text-slate-400" title={row.businessName}>{row.businessName}</td><td className="px-3 text-cyan-200">{AGENT_LABELS[row.agentType] ?? row.agentType}</td><td className="px-3"><TaskStatus status={row.status} /></td><td className="px-3 font-mono">{taskDuration(row.durationMs)}</td><td className="px-3 font-mono text-slate-400">{adminTime(row.createdAt)}</td><td className="px-3"><button aria-expanded={expanded} onClick={toggle} className="text-cyan-300 hover:text-cyan-100">{expanded ? "收起" : "查看"}</button></td></tr>{expanded && <tr><td colSpan={7} className="border-b border-white/5 bg-[#061a2d] p-4"><div className="space-y-2 text-xs"><p className="break-all text-slate-500">任务编号：{row.id}</p><p className="text-slate-400">提供方：{row.providerId ?? "未记录"} · 结束时间：{row.completedAt ? adminTime(row.completedAt) : "尚未结束"}</p><p className={row.errorSummary ? "break-words text-rose-300" : "text-slate-400"}>错误摘要：{row.errorSummary ?? "无错误摘要"}</p></div></td></tr>}</>;
}
